# Generated by Django 2.2 on 2019-04-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
